### PR TITLE
fix(doom): Adjust cursor position for multibyte charsets in menu entry

### LINKED ISSUE #422: Misaligned cursor position with the Doom theme for some entries
**Describe the bug**

In the Doom theme, with some fonts icons, the cursor position isn't aligned with
the first character of the menu entry:

Misaligned Cursor

**To Reproduce**

1. Use a font with variant width glyphs like: [FiraCode](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip) form Nerd Fonts. For the screenshots I use `FiraCodeNerdFont-Medium.ttf`
2. Run the minimal config with `nvim -u repro.lua`:

```lua
-- repro.lua
local root = vim.fn.fnamemodify("./repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  {
    "nvimdev/dashboard-nvim",
    event = "VimEnter",
    opts = function()
      local opts = {
        theme = "doom",
        config = {
          header = { "HEADER" },
          center = {
            { action = "ene | startinsert", desc = " Aligned", icon = " ", key = "e", },
            { action = "Lazy", desc = " Not aligned", icon = "󰒲 ", key = "<leader>cl", },
            { action = "qa", desc = " Aligned", icon = " ", key = "q" },
          },
        },
      }
      return opts
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

3. Restart neovim or close the Lazy float window and run `:Dashboard`.
3. Scroll down and up through the menu entries.
4. At the `Not aligned` entry the cursor should be at the left of the character `N`.

**Expected behavior**

Correctly align the cursor regardless of the icon used:

Aligned Cursor

---

**System info**

Konsole: 23.08.4
Gentoo Linux 2.14
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.6.13-gentoo (64-bit)

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

```
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include
```

### PR DESCRIPTION
**Pull request by polirritmico**
This should fix #422. There is a problem with multibyte charsets (like some nerd-fonts icons), cause Lua count the bytes and not the chars of a string (At least with [Lua 5.2](https://www.lua.org/manual/5.2/manual.html#2.1)). In this case, even if `col` is the correct position, its not counting the extra byte of the icon character.

This PR adds a `delta` value that would insert an offset to the `col` value when needed.

Regards

### CODE REVIEW

File: lua/dashboard/theme/doom.lua [hunk 1]
```diff
@@ -129,7 +129,12 @@ local function generate_center(config)
           curline = curline + (before > curline and -1 or 1)
         end
         before = curline
-        api.nvim_win_set_cursor(config.winid, { curline, col })
+
+        -- FIX: #422: In Lua the length of a string is the numbers of bytes not
+        -- the number of characters.
+        local curline_str = api.nvim_buf_get_lines(config.bufnr, curline - 1, curline, false)[1]
+        local delta = curline_str:len() - vim.api.nvim_strwidth(curline_str) - 2
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:136]:
```suggestion
        local delta = curline_str:len() - api.nvim_strwidth(curline_str) - 2
```
