### PR TITLE
fix(plugin): don't load if read from stdin

### LINKED ISSUE #443: [BUG] Piped standard output to neovim shows the dashboard instead of the buffer with stdout content
**Describe the bug**
Whenever stdout is piped to neovim, it shows the dashboard instead of the buffer that contains the piped stdout.

This was not an issue in `63df284`.

**To Reproduce**
1. Run `echo "hello" | nvim`
2. It shows the dashboard instead of the piped stdout

**Expected behavior**
The piped stdout should be written to the buffer.

**Screenshots**

Before (`63df284`): 

dashboard-before

After (`39f308a`):

dashbaord-after

### PR DESCRIPTION
**Pull request by mangkoran**
As this plugin now uses StdinReadPre, user shouldn't lazy-load this plugin

Fix #443

### CODE REVIEW

**Comment by mangkoran** [comment]
Friendly mention @glepnir :D

File: plugin/dashboard.lua [hunk 1]
```diff
@@ -1,14 +1,22 @@
 -- version 0.2.3
-if vim.g.loaded_dashboard then
-  return
-end
 
-vim.g.loaded_dashboard = 1
+vim.api.nvim_create_augroup('dashboard', { clear = true })
```
Comment (glepnir) [inline plugin/dashboard.lua:3]: there will return id for group

File: plugin/dashboard.lua [hunk 2]
```diff
@@ -1,14 +1,22 @@
...
+
+vim.api.nvim_create_autocmd('StdinReadPre', {
```
Comment (glepnir) [inline plugin/dashboard.lua:5]: use StdinReadPre how the startup time take ?

Comment (mangkoran) [reply plugin/dashboard.lua:5]: wezterm-gui_NhQ5wDDQkC

master
- 14.019
- 13.470
- 14.572
- 13.177
- 14.534

wezterm-gui_IpOp9sPI73

pr
- 13.668
- 14.700
- 12.355
- 18.011
- 12.677

File: plugin/dashboard.lua (hunk 1 above)
Comment (mangkoran) [reply plugin/dashboard.lua:3]: Should we save and use the group id? I use `group` name [here](https://github.com/nvimdev/dashboard-nvim/pull/450/files#diff-3fd880e15253451a204b448a20fc498b4cfc6e9ace903c3dfaefb8bd29dfea1dR6) instead of id.

Comment (mangkoran) [reply plugin/dashboard.lua]: Updated, please kindly check

File: plugin/dashboard.lua (hunk 2 above)
Comment (glepnir) [reply plugin/dashboard.lua:5]: I think you can just use --startuptime. and i am plan to add new api in core to get startuptime

**Review by glepnir — APPROVED** [review]
